CREATE TABLE IF NOT EXISTS flight_seats (
id SERIAL PRIMARY KEY,
flight_id BIGINT NOT NULL REFERENCES flights(id) ON DELETE CASCADE,
seat_number VARCHAR(10) NOT NULL,
seat_class VARCHAR(20) NOT NULL,
occupied BOOLEAN DEFAULT FALSE
)