CREATE TABLE IF NOT EXISTS airports (
id SERIAL PRIMARY KEY,
name_airport VARCHAR(255) NOT NULL,
country_airport VARCHAR(255) NOT NULL,
city_airport VARCHAR(255) NOT NULL,
code VARCHAR(10) UNIQUE NOT NULL);