INSERT INTO airports (name_airport, city_airport, country_airport, code) VALUES
('Paris Charles de Gaulle', 'Paris', 'France', 'CDG'),
('Paris Orly', 'Paris', 'France', 'ORY'),
('London Heathrow', 'London', 'United Kingdom', 'LHR'),
('London Gatwick', 'London', 'United Kingdom', 'LGW'),
('Frankfurt Airport', 'Frankfurt', 'Germany', 'FRA'),
('Berlin Brandenburg', 'Berlin', 'Germany', 'BER'),
('Amsterdam Schiphol', 'Amsterdam', 'Netherlands', 'AMS'),
('Madrid Barajas', 'Madrid', 'Spain', 'MAD'),
('Barcelona El Prat', 'Barcelona', 'Spain', 'BCN'),
('Milan Malpensa', 'Milan', 'Italy', 'MXP'),
('Rome Fiumicino', 'Rome', 'Italy', 'FCO'),
('Athens International', 'Athens', 'Greece', 'ATH'),
('Zurich Airport', 'Zurich', 'Switzerland', 'ZRH'),
('Vienna International', 'Vienna', 'Austria', 'VIE'),
('Budapest Liszt Ferenc', 'Budapest', 'Hungary', 'BUD'),
('New York John F. Kennedy', 'New York', 'USA', 'JFK'),
('Newark Liberty', 'Newark', 'USA', 'EWR'),
('Los Angeles', 'Los Angeles', 'USA', 'LAX'),
('San Francisco', 'San Francisco', 'USA', 'SFO'),
('Chicago O’Hare', 'Chicago', 'USA', 'ORD'),
('Toronto Pearson', 'Toronto', 'Canada', 'YYZ'),
('Vancouver International', 'Vancouver', 'Canada', 'YVR'),
('Dubai International', 'Dubai', 'UAE', 'DXB'),
('Abu Dhabi International', 'Abu Dhabi', 'UAE', 'AUH'),
('Hamad International', 'Doha', 'Qatar', 'DOH'),
('Indira Gandhi Delhi', 'Delhi', 'India', 'DEL'),
('Mumbai International', 'Mumbai', 'India', 'BOM'),
('Tokyo Haneda', 'Tokyo', 'Japan', 'HND'),
('Tokyo Narita', 'Tokyo', 'Japan', 'NRT'),
('Seoul Incheon', 'Seoul', 'South Korea', 'ICN'),
('Singapore Changi', 'Singapore', 'Singapore', 'SIN'),
('Hong Kong International', 'Hong Kong', 'China', 'HKG'),
('Cape Town International', 'Cape Town', 'South Africa', 'CPT'),
('Johannesburg OR Tambo', 'Johannesburg', 'South Africa', 'JNB'),
('Cairo International', 'Cairo', 'Egypt', 'CAI'),
('Sydney Kingsford Smith', 'Sydney', 'Australia', 'SYD'),
('Melbourne Airport', 'Melbourne', 'Australia', 'MEL'),
('Auckland Airport', 'Auckland', 'New Zealand', 'AKL')
ON CONFLICT DO NOTHING;
